### ISSUE TITLE
Chapter 7 Typos, Part 1

### ISSUE THREAD

**Issue by jlgraner** [labarlab/labarlab.github.io#10]
7.3
Admin (i.e. all) privileges are needed by the user to create an database.
to
Admin (i.e. all) privileges are needed by the user to create a database.

7.4.1
When a certain value, such as a participant ID or emotion name, show up across multiple...
to
When a certain value, such as a participant ID or emotion name, shows up across multiple...

7.4.2
...thus begin to make our database relational.
to
...thus beginning to make our database relational.

...containing four columns – one for the subject...
to
...containing four columns – one each for subject...

...if it was desired to keep the question syntax...
to
...if it were desired to keep the question syntax...

7.4.3
...not understanding column names nor knowing what data they contain.
to
...not understanding column names or not knowing what data they contain.

...definitions or explanations of column names and purpose.
to
...definitions or explanations of column names and purposes.

Additional columns can be add using the col_ format, when required.
to
Additional columns can be added using the col_ format, when required.

**Comment by nmuncy** [comment]
Updated, changes will reflect in next release
