### ISSUE TITLE
7.5 Insert Data Code Bug?

### ISSUE THREAD

**Issue by jlgraner** [labarlab/labarlab.github.io#11]
The following example of inserting data failed:
![image](https://github.com/labarlab/labarlab.github.io/assets/32852039/34fac45c-7804-4003-b539-6d5fc63479eb)

**Comment by jlgraner** [comment]
When I try without the "ignore" option, I get this error:
ERROR 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`db_test_name`.`tbl_erq`, CONSTRAINT `tbl_erq_ibfk_2` FOREIGN KEY (`sess_id`) REFERENCES `ref_sess` (`sess_id`))

**Comment by nmuncy** [comment]
Ahh, values are required in `ref_sess`

**Comment by nmuncy** [comment]
also, this can be helpful `show warnings\g`
