### ISSUE TITLE
Chapter 7.1 Example Error

### ISSUE THREAD

**Issue by jlgraner** [labarlab/labarlab.github.io#9]
The example code from section 7.1 granting specific permissions produced an error:
![image](https://github.com/labarlab/labarlab.github.io/assets/32852039/c6c51ca6-6233-40e8-9471-9da7502cfda6)

The example granting all permissions did work.

**Comment by nmuncy** [comment]
Issue resulted from extra comma after `create temporary tables`

```
mysql> grant insert, update, select, references, create temporary tables on db_test.* to 'test'@'localhost';
Query OK, 0 rows affected (0.00 sec)
```
